### ISSUE TITLE
Dilbert daily strip broken

### ISSUE THREAD

**Issue by Garfield-lover** [ameboide/webcomic_reader#28]
Since they "optimized" the layout of dilbert.com for tablet use, the webcomic_reader script doesn't work anymore there.
Ok, maybe I'm just too simple-minded, but apparently I'm not able to configure this script in order to let it work again on dilbert.com.
Any help (also directions to the proper forum) would be highly appreciated. Thanks!

**Comment by ameboide** [comment]
I figured it doesn't make much sense to use the script on the main page now, but if you click on a single strip it will take you to a traditional daily strip format. I enabled the script there :)

The script was originally hosted at [userscripts.org](http://userscripts.org/scripts/show/59842) (R.I.P.), and currently is also hosted at [openuserjs.org](https://openuserjs.org/scripts/ameboide/Webcomic_Reader) and [greasyfork.org](https://greasyfork.org/scripts/3008-webcomic-reader). It looks like openuserjs has more installs but no one comments there, everyone goes to [greasyfork](https://greasyfork.org/en/scripts/3008-webcomic-reader/feedback)
