### ISSUE TITLE
Force next image even if it cant be loaded

### ISSUE THREAD

**Issue by pythonimus** [ameboide/webcomic_reader#32]
Hi,
it would be great if there was some function to force the reader to the next image even if that image is not fully loaded or could not be found etc.

For example on g.e-hentai.org: The navigation buttons of the original style are overwritten with the reader functionality. If an image is corrupt in a gallery the reader will hang and there is no way to click on the "click here if image does not load" button because I cannot get to said image.

**Comment by ameboide** [comment]
There's a setting called "Force loading next page" that does just that :smiley:
