### ISSUE TITLE
mangacow.co doesnt work

### ISSUE THREAD

**Issue by NLZ** [ameboide/webcomic_reader#34]
It seems mangacow.co has changed, so it doesnt work any more. The other sites that used to share the settings with it (mangadoom.co, omgmanga.com) are still working.
I tried to follow the tutorial (http://userscripts-mirror.org/topics/86377#posts-380342) but my basic understanding of websites couldnt help me to figure it out.
Can you help me to make the it work?

**Comment by alkumaish** [comment]
Fixed it in https://github.com/ameboide/webcomic_reader/pull/36
It's an easy fix.

**Comment by NLZ** [comment]
Sweet, thanks :)
